### ISSUE TITLE
Use setup-python to speed up the pipelines

### ISSUE THREAD

**Issue by paolodelia99** [samueledelia/py-exopricer#23]
Use [setup-python](https://github.com/actions/setup-python) step in the github actions, which by leveraging the caching of the dependendenices, can speed up the initial set up.
Example:

**Caching pip dependencies:**

```yaml
steps:
- uses: actions/checkout@v4
- uses: actions/setup-python@v5
  with:
    python-version: '3.9'
    cache: 'pip' # caching pip dependencies
- run: pip install -r requirements.txt
```
